##-----------服务基本信息配置-------------------##
spring:
  application:
    name: journey-system-consume #服务的名字
##-----------eureka配置-------------------##
eureka:
  client:
    service-url:
       defaultZone: http://pangbohuan:pbh.3644@127.0.0.1:8761/eureka,
                                http://pangbohuan:pbh.3644@127.0.0.1:8762/eureka,
                                http://pangbohuan:pbh.3644@127.0.0.1:8763/eureka #注册到eureka服务
##-----------feign配置-------------------##
feign:
  httpclient:
    enabled: false #禁用JDK自带的httpclient
  okhttp:
    enabled: true #启用okhttp
  hystrix:
    enabled: true #启用hystrix熔断机制
##-----------redis配置-------------------##
redis:
  database: 0 # Redis数据库索引（默认为0）
  host: 127.0.0.1  #Redis服务器地址
  port: 6379 # Redis服务器连接端口
  password: # Redis服务器连接密码（默认为空）
  pool:
    max-active: 20 # 连接池最大连接数（使用负值表示没有限制）
    max-idle: 10 # 连接池中的最大空闲连接
    max-wait: 1000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    min-idle: 5 # 连接池中的最小空闲连接
    timeout: 2000 # 连接超时时间（毫秒）

