server:
  port: 8080
eureka:
  client:
    service-url:
            defaultZone: http://pangbohuan:pbh.3644@127.0.0.1:8761/eureka,
                          http://pangbohuan:pbh.3644@127.0.0.1:8762/eureka,
                          http://pangbohuan:pbh.3644@127.0.0.1:8763/eureka #注册到eureka服务
spring:
  application:
    name: journey-system-zuul